# Generated by Django 5.1a1 on 2024-06-02 16:57

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('mail_id', models.EmailField(max_length=254)),
                ('dipartment', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('employee_pic', models.FileField(default='', max_length=250, null=True, upload_to='employee/pic')),
                ('employee_details', tinymce.models.HTMLField()),
            ],
        ),
    ]
